name = "uglink-worker"
main = "dist/index.js"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]
[vars]
BASE_URL = "https://192-168-0-2.tianyi0403.direct.ug.link:9443/"
PORT = "2283"
USERNAME = "tianyi"

[[kv_namespaces]]
binding = "UGLINK_CACHE"
id = "67e768e03e9b4414b504e47e271944a4"  # Replace with your actual KV namespace ID from Cloudflare dashboard

[observability.logs]
enabled = true
