name = "test"
main = "dist/index.js"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]
[vars]
BASE_URL = "https://tianyi0403.cn29.ug.link/"
PORT = "2283"
USERNAME = "tianyi"

[[kv_namespaces]]
binding = "UGLINK_CACHE"
id = "67e768e03e9b4414b504e47e271944a4"  # Replace with your actual KV namespace ID from Cloudflare dashboard

[observability.logs]
enabled = true
